---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: bggns
  labels:
    app: bggapp
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: bggapp
  template:
    metadata:
      name: bggapp-pod
      namespace: bggns
      labels:
        app: bggapp
    spec:
      containers:
        - name: bggapp-container
          image: stackupiss/bgg-backend:v2
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            periodSeconds: 60
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: bgg-cm
            - secretRef:
                name: bgg-secret
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
  labels:
    app: bggapp
spec:
  type: ClusterIP
  selector:
    app: bggapp
  ports:
    - name: web
      port: 8080
      targetPort: 3000