---
apiVersion: v1
kind: Namespace
metadata:
  name: minio-ns

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-cm
  namespace: minio-ns
  labels:
    app: minio
data:
  MINIO_ROOT_USER: admin
  MINIO_DATA_DIR: /data
  MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
  MINIO_DISTRIBUTED_NODES: minio-sts-{0...3}.minio-hsvc.minio-ns.svc.cluster.local/data
  MINIO_API_PORT_NUMBER: "9000"
  MINIO_CONSOLE_PORT_NUMBER: "9090"
  BITNAMI_DEBUG: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio-ns
  labels:
    app: minio
type: Opaque
data:
  MINIO_ROOT_USER: YWRtaW4= # admin
  MINIO_ROOT_PASSWORD: Y2hhbmdlaXQ= # changeit

---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: minio-ns
  labels:
    app: minio
    name: minio-svc 
spec:
  type: ClusterIP
  selector:
    app: minio
    name: minio-po
  ports:
  - name: data-port
    port: 9000
    targetPort: 9000
  - name: console-port
    port: 9090
    targetPort: 9090
  
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-sts
  namespace: minio-ns 
  labels:
    app: minio
    name: minio-sts
spec:
  replicas: 4
  serviceName: minio-hsvc
  selector:
    matchLabels:
      app: minio
      name: minio-po
  volumeClaimTemplates:
  - apiVersion: v1 
    kind: PersistentVolumeClaim 
    metadata:
      name: data-vol
    spec:
      accessModes: 
       - ReadWriteOnce
      storageClassName: do-block-storage
      resources: 
        requests: 
          storage: 1Gi
  template:
    metadata:
      name: minio-po
      labels:
        app: minio
        name: minio-po
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: minio-container
        image: bitnami/minio:2024.11.7
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: minio-cm
        - secretRef:
            name: minio-secret
        ports:
        - name: data-port
          containerPort: 9000
        - name: web-port
          containerPort: 9090
        resources:
          limits:
            cpu: 200m
            memory: 250Mi
          requests:
            cpu: 200m
            memory: 250Mi
        volumeMounts:
          - name: data-vol 
            mountPath: /data

---
apiVersion: v1
kind: Service
metadata:
  name: minio-hsvc
  namespace: minio-ns
  labels:
    app: minio
    name: minio-svc 
spec:
  clusterIP: None
  selector:
    app: minio
    name: minio-po
  ports:
  - name: data-port
    port: 9000
    targetPort: 9000
  - name: console-port
    port: 9090
    targetPort: 9090

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-data-ing
  namespace: minio-ns
  labels:
    app: minio
    name: minio-ing
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "5"
spec:
  ingressClassName: nginx
  rules:
  - host: data-146.190.202.36.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-svc
            port:
              name: data-port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console-ing
  namespace: minio-ns
  labels:
    app: minio
    name: minio-ing
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "5"
spec:
  ingressClassName: nginx
  rules:
   - host: console-146.190.202.36.nip.io
     http:
       paths:
       - path: /
         pathType: Prefix
         backend:
           service:
             name: minio-svc
             port:
               name: console-port
  